# FIREFLY 6
originator: 'Pixxel'
spacecraft_id: "FF06"

spacecraft_parameters:
    name: 'Firefly_6'
    internal_code: "SAT00"
    norad_id: 91696 # KSAT ID
    mass: 50.03 # kg
    min_visibility_elevation: 5.0 #deg

    maneuver_parameters:
      heater_duration: 40 # min
      max_delta_v: 0.8 # m/s

tle_parameters:
    classification: "U"
    launch_year : 2025
    launch_number: 14
    launch_piece: "ZZ"
    ephemeris_type: 0 # DEFAULT
    element_number: 0
    leafspace_id : 10009

orbital_parameters:
  semimajor_axis: 6943.432 #km
  mean_altitude: 565.295 #km
  inclination: 97.652 #deg
  eccentricity: 0.00106
  raan: -71.972783 #deg
  period: 5765.332 #sec

hardware_parameters:
  gps_to_utc_offset : -18


imaging_parameters:
    max_offnadir : 20 # deg
    quat_body2cam: [0.7055250757429985, -0.0102042385418456,  0.0054122797088059, -0.7085908186266394]
    camera_parameters:
        EFL: 0.605
        Pixxel_Pitch: 5.5e-6

integrator_config:
  min_step: 0.001
  max_step: 300
  pos_error: 10  # in metres

forces:
  gravity_harmonics:
    bodies:
      earth:
        enable: True
        model: 'eigen-6s'
        degree: 33
        order: 33
      moon:
        enable: False
        model: 'GL0660B'
        degree: 10
        order: 10
  third_bodies:
    enable: True
    bodies:
      - sun
      - moon
      - mars
      - jupiter
  drag:
    enable: True
    cd: 2.2
    area: 0.8
    activity: 'AVERAGE'
  srp:
    enable: True
    area: 0.8
    reflection: 1.8
    # absorption: 1
sensor_parameters:
  star_tracker:
    direction: [0, 0.766, -0.642]
    cfov_half_angle: 40
    angular_margin: 0.0
